export type ProfitabilityAnalysis = {
  totalRevenue: number;
  totalExpenses: number;
  netProfit: number;
  marginPercentage: number;
};

export type FinancialSummary = {
  period: string;
  totalRevenueDZD: number;
  totalRevenueSAR: number;
  expensesDZD: number;
  expensesSAR: number;
};

type AmountLike = { amount?: number | null; amount_dzd?: number | null };

export function calculateProfitability(_bookings: unknown[], payments: AmountLike[], expenses: AmountLike[]): ProfitabilityAnalysis {
  const totalRevenue = payments.reduce((sum, p) => sum + Number(p.amount ?? p.amount_dzd ?? 0), 0);
  const totalExpenses = expenses.reduce((sum, e) => sum + Number(e.amount ?? e.amount_dzd ?? 0), 0);
  const netProfit = totalRevenue - totalExpenses;
  return { totalRevenue, totalExpenses, netProfit, marginPercentage: totalRevenue > 0 ? (netProfit / totalRevenue) * 100 : 0 };
}

export function generateInvoice(): never {
  throw new Error('Invoices must be generated by public.create_invoice_transaction');
}

export function processRefund(): never {
  throw new Error('Refunds must be processed through the server-side reversal workflow');
}

export function getFinancialSummary(): never {
  throw new Error('Financial summaries must be queried from Supabase');
}

export function calculateRevenuePerPilgrim(bookings: Array<{ total_dzd?: number | null; amount_dzd?: number | null; }>) {
  if (bookings.length === 0) return 0;
  const totalRevenue = bookings.reduce((sum, b) => sum + Number(b.total_dzd ?? b.amount_dzd ?? 0), 0);
  return totalRevenue / bookings.length;
}
