-- The two staff-scope helpers the rest of the ledger has always assumed existed.
--
-- public.current_staff_agency_id() and public.current_staff_branch_id() are named
-- 147 times in this directory: as the DEFAULT on agency_id for most tenant tables,
-- inside every policy generated by 20260428121700, in the export and storage
-- policies, and in a handful of SECURITY DEFINER bodies. Neither was ever created
-- by a migration. 103 of those references are DDL, which resolves the function at
-- the moment it runs, so `supabase db reset` stopped at
-- 20260403172600_finalize_function_execute_security.sql:6 --
--
--     revoke all on function public.current_staff_agency_id() from public, anon, authenticated;
--
-- -- with 42883, and had done since April. The live database carries both
-- functions, typed into a SQL editor once and never written down, which is exactly
-- why nothing looked broken: the only gate that replays from migrations alone
-- needs Docker, and Docker has never been available on the machine doing the work.
-- scripts/verify-migrations.mjs now fails on this whole class of defect -- a
-- function or relation that DDL needs and no earlier migration creates -- so it
-- cannot recur silently.
--
-- Placed here, immediately after 20260324000300, because that is the earliest
-- point at which the bodies resolve (it adds staff_profiles.branch_uuid at line 42
-- and defines the sibling helpers at 164-195) and the latest point still ahead of
-- the first use.
--
-- Semantics are staff_agency_id() and staff_branch_id() verbatim: same table, same
-- predicate, same NULL for a session with no active staff profile. Unlike the
-- boolean and text guards that 20260830140000 had to make total, that NULL fails
-- closed everywhere a uuid lands:
--
--   * `agency_id = null` in a policy USING clause is NULL, so the row is filtered
--     away rather than returned;
--   * the same expression in WITH CHECK is a violation, because Postgres rejects
--     a WITH CHECK that evaluates to false *or* null;
--   * a NULL DEFAULT on a `not null` column raises 23502 instead of writing a row
--     into an agency nothing can reach again.
--
-- The one shape where the NULL did not fail closed was a body comparing with
-- `<>`, in 20260509100100. That comparison is repaired in the same migration that
-- repaired the boolean guards' `and staff_role() <> 'ADMIN'`.
create or replace function public.current_staff_agency_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select agency_id from public.staff_profiles
  where user_id = auth.uid() and is_active = true limit 1;
$$;

create or replace function public.current_staff_branch_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select branch_uuid from public.staff_profiles
  where user_id = auth.uid() and is_active = true limit 1;
$$;

-- Internal helpers are not API endpoints. Revoked at the point of creation rather
-- than eighty migrations later, so there is no window in which a replayed database
-- has them exposed. 20260331100100 and 20260403172600 both revoke them again;
-- revoking twice is free.
revoke all on function public.current_staff_agency_id() from public, anon, authenticated;
revoke all on function public.current_staff_branch_id() from public, anon, authenticated;
